---

- hosts: all
  gather_facts: false
  tasks:
    - name: Install Python
      raw: test -e /usr/bin/python || (apt update && apt install -y python)
      register: test
      changed_when: test.stdout

- hosts: all
  roles:
    - updates
    - user
    - ssh
    - ufw