---

- name: Update existing packages
  apt:
    update_cache: yes
    upgrade: safe
    autoremove: yes

- name: Install unattended-upgrades package
  apt:
    name: unattended-upgrades
    update_cache: yes
    state: latest

- name: Enable unattended upgrades
  copy:
    src: ./config/apt/10updates
    dest: /etc/apt/apt.conf.d/10updates
    owner: root
    group: root
    mode: 0644